### DISCUSSION TITLE
Is it possible to customize the RPC endpoint path?

### DISCUSSION THREAD

**Discussion by Gumichocopengin8** [connectrpc/connect-es#1409] [Q&A] [answered]
I use `Buf` to generate TS code, and my server RPC endpoint is like`localhost:8000/rpcName` instead of `localhost:8000/packageName.ServiceName/rpcName`. However, the generated code uses `localhost:8000/packageName.ServiceName/rpcName`. I wanna change it to `localhost:8000/rpcName` style. Is it possible to do this?

```yaml
# buf.gen.yaml
version: v2
plugins:
  - local: protoc-gen-es
    out: src/proto_gen
    include_imports: true
    opt: target=ts
```
