### ISSUE TITLE
createPromiseClient Not assignable to parameter of type ServiceType

### ISSUE THREAD

**Issue by runar-rkmedia** [connectrpc/connect-es#1160]
**Describe the bug**

I tried to create a very basic client from a .proto-file with a single method, but `createPromiseClient(FeedService, transport)` results in the error below.

```
typescript: Argument of type 'GenService<{ getChannels: { methodKind: "unary"; input: GenMessage<ChannelsRequest>; output: GenMessage<ChannelsResponse>; }; }>' is not assignable to parameter of type 'ServiceType'.
  Types of property 'methods' are incompatible.
    Type 'DescMethod[]' is not assignable to type '{ [localName: string]: MethodInfo<AnyMessage, AnyMessage>; }'.
      Index signature for type 'string' is missing in type 'DescMethod[]'. [2345]
ts: Argument of type 'GenService<{ getChannels: { methodKind: "unary"; input: GenMessage<ChannelsRequest>; output: GenMessage<ChannelsResponse>; }; }>' is not assignable to parameter of type 'ServiceType'.
  Types of property 'methods' are incompatible.
    Type 'DescMethod[]' is not assignable to type '{ [localName: string]: MethodInfo<AnyMessage, AnyMessage>; }'.
      Index signature for type 'string' is missing in type 'DescMethod[]'. [2345]
```

Could this be due to some of the newly released v2 of [protobuf-es](https://github.com/bufbuild/protobuf-es/releases/tag/v2.0.0) ?

**Environment**
├── @bufbuild/buf@1.35.1
├── @bufbuild/protobuf@2.0.0
├── @bufbuild/protoc-gen-es@2.0.0
├── @connectrpc/connect@1.4.0
├── @connectrpc/connect-web@1.4.0
├── @connectrpc/protoc-gen-connect-es@1.4.0
package-manager: bun 1.1.17
node: v20.15.0

**To Reproduce**

Full source-code is available at https://github.com/runar-rkmedia/audio-mirror/tree/03db0de69b254e20f9fb6c77c712696e4055e333

<summary><code>buf.gen.yaml</code>
<details>
```yaml
version: v2
plugins:
  - local: protoc-gen-go
    out: gen
    opt: paths=source_relative
  - local: protoc-gen-connect-go
    out: gen
    opt: paths=source_relative
  - local: frontend/node_modules/.bin/protoc-gen-es
    out: frontend/src/gen
    opt: target=ts
  - local: frontend/node_modules/.bin/protoc-gen-connect-es
    out: frondend/src/gen
    # Add more plugin options here
    opt: target=ts
```
</details>
</summary>

<summary><code>pods.proto</code>
<details>
```proto
syntax = "proto3";

package api.v1;

option go_package = "github.com/runar-rkmedia/audio-mirror/gen/api/v1;apiv1";

message ChannelsRequest {
  ChannelType type = 1;
}

enum ChannelType {
  CHANNEL_TYPE_UNSPECIFIED = 0;
  CHANNEL_TYPE_PODCAST = 1;
  CHANNEL_TYPE_BOOKS = 2;
}

message Channel {
  string id = 1;
  ChannelType type = 2;
  string title = 3;
  string description = 4;
  string image_url = 5;
}

message ChannelsResponse {
  repeated Channel channels = 1;
}

service FeedService {
  rpc GetChannels(ChannelsRequest) returns (ChannelsResponse) {}
}
```
</details>
</summary>

<summary><code>apiclient.ts</code>
<details>
```ts
import { createPromiseClient } from '@connectrpc/connect'
import { createConnectTransport } from '@connectrpc/connect-web'

// Import service definition that you want to connect to.
import { FeedService } from '../gen/api/v1/pods_pb'

// The transport defines what type of endpoint we're hitting.
// In our example we'll be communicating with a Connect endpoint.
// If your endpoint only supports gRPC-web, make sure to use
// `createGrpcWebTransport` instead.
const transport = createConnectTransport({
	baseUrl: 'http://localhost:8080'
})

// Here we make the client itself, combining the service
// definition with the transport.
const apiClient = createPromiseClient(FeedService, transport)

export default apiClient

```
</summary>
</details>
