### ISSUE TITLE
Failing to generate proper types v1.4.0

### ISSUE THREAD

**Issue by ZanzyTHEbar** [connectrpc/connect-es#1215]
**Describe the bug**

1. My connect project is generating typescript files for me, but the `crearePromiseClient` returns a `Promise<unknown>`. 

Which doesn't make sense, as that should be passed down via the generic.

2. My `product_connect.ts` file has multiple errors: 

`Module '"@bufbuild/protobuf"' has no exported member 'MethodKind'.`

All `I` and `O` members have a `'X' only refers to a type, but is being used as a value here.`

**To Reproduce**

Install the deps, spin up a base-bones project based on the example using the newest version of the protoc plugin.

**Environment (please complete the following information):**

- @connectrpc/connect-web version: 1.4.0
- Frontend framework and version: @solid-js: 1.8.11
- Node.js version: 22.4.0

If your problem is specific to bundling, please also provide the following information:

- Bundler and version: @vite: 5.4.3
- Bundler plugins and version: vite-plugin-solid: 2.10.2
- Bundler configuration file:

```ts
import { resolve } from 'path';
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';
import devtools from 'solid-devtools/vite';

export default defineConfig({
  resolve: {
    alias: {
      '@interfaces': resolve(__dirname, './src/interfaces'),
      '@components': resolve(__dirname, './src/components'),
      '@redux': resolve(__dirname, './src/redux'),
      '@pages': resolve(__dirname, './src/pages'),
      '@styles': resolve(__dirname, './src/styles'),
      '@config': resolve(__dirname, './src/config'),
      '@src': resolve(__dirname, './src'),
      '@assets': resolve(__dirname, './assets'),
      '@hooks': resolve(__dirname, './src/utils/hooks'),
      '@static': resolve(__dirname, './src/static'),
      '@utils': resolve(__dirname, './src/utils'),
    },
  },
  plugins: [
    devtools(),
    solidPlugin(),
  ],
  server: {
    port: 3000,
    host: true,
    strictPort: true,
  },
  build: {
    target: 'esnext',
  },
});
```

**Additional context**
 Here are my relevant files: 
 
> buf.yaml
 ```yaml
 # For details on buf.yaml configuration, visit https://buf.build/docs/configuration/v2/buf-yaml
version: v2

lint:
    use:
        - DEFAULT
breaking:
    use:
        - FILE
 ```
 > buf.gen.yaml
  ```yaml
  version: v2
plugins:
    - local: protoc-gen-go
      out: ../backend/pkgs/gen
      opt:
          - paths=source_relative
    - local: protoc-gen-connect-go
      out: ../backend/pkgs/gen
      opt:
          - paths=source_relative
    - local: protoc-gen-es
      out: ../frontend/src/static/types/gen
      opt:
          - target=ts
          - ts_nocheck=false
    - local: protoc-gen-connect-es
      out: ../frontend/src/static/types/gen
      opt:
          - target=ts
          - ts_nocheck=false
  ```
  > product.proto
  ```proto
  syntax = "proto3";

package product.v1;

option go_package = "github.com/ZanzyTHEbar/goflexpro/pkgs/gen/product/v1";

message ProductDTO {
  int32 id = 1;
  string name = 2;
  string description = 3;
  double price = 4;
  string created_at = 5;
}

message CreateProductRequest { repeated ProductDTO product = 1; }

message CreateProductResponse { repeated bool success = 1; }

message GetProductRequest { repeated int32 id = 1; }

message GetProductResponse { repeated ProductDTO product = 1; }

message UpdateProductRequest { repeated ProductDTO product = 1; }

message UpdateProductResponse { repeated bool success = 1; }

message DeleteProductRequest { repeated int32 id = 1; }

message DeleteProductResponse { repeated bool success = 1; }

service ProductService {
  rpc CreateProduct(CreateProductRequest) returns (CreateProductResponse);
  rpc GetProduct(GetProductRequest) returns (GetProductResponse);
  rpc UpdateProduct(UpdateProductRequest) returns (UpdateProductResponse);
  rpc DeleteProduct(DeleteProductRequest) returns (DeleteProductResponse);
}
```
