### ISSUE TITLE
Migration problems cannot generate protos any longer

### ISSUE THREAD

**Issue by go-aegian** [connectrpc/connect-es#1337]
I followed all steps to migrate and I'm also using knit

**npx @connectrpc/connect-migrate@latest**
```
Scanning... ✓
    1 package.json file
    0 lock files
    0 source files
    1 buf.gen.yaml file
It looks like you are already up to date 
```

But I'm getting these errors when generating protos

**npx buf generate**
```
Failure: decode buf.gen.yaml: invalid as version v2: could not unmarshal as YAML: yaml: unmarshal errors:
  line 4: field name not found in type bufconfig.externalGeneratePluginConfigV2
  line 7: field name not found in type bufconfig.externalGeneratePluginConfigV2
  line 10: field name not found in type bufconfig.externalGeneratePluginConfigV2
  line 16: field name not found in type bufconfig.externalGeneratePluginConfigV2
```

**buf.gen.yaml** 

```
version: v2
clean: true
plugins:
  - name: go
    out: ../pb
    opt: paths=source_relative
  - name: connect-go
    out: ../pb
    opt: paths=source_relative
  - name: es
    out: ../pb/web
    opt:
      - target=ts
  - name: knit-ts
    out: ../pb/web
    opt:
      - target=ts
```

**buf.yaml**
```
version : v2
lint    :
  use   :
    - DEFAULT
  except:
    - PACKAGE_DIRECTORY_MATCH
    # Relations re-use request and response message names for conciseness.
    - RPC_REQUEST_RESPONSE_UNIQUE
    - RPC_REQUEST_STANDARD_NAME
    - RPC_RESPONSE_STANDARD_NAME
breaking:
  use:
    - FILE
```

Anybody can provide me with help?
